name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'Squirrel3', destination: 'platform=iOS Simulator,OS=16.2,name=iPhone 8' }
          - { scheme: 'Squirrel3', destination: 'platform=macOS,arch=x86_64' }

    steps:
    - uses: actions/checkout@v2

    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: List available schemes
      run: xcodebuild -list

    - name: Show Build Settings
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

    - name: Show Available Destinations
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    - name: Build
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
